### ISSUE TITLE
incorrect download info

### ISSUE THREAD

**Issue by TeaKave** [akexorcist/SnapTimePicker#1]
Hi. I had a problem following your instructions to download the time picker to my project. It would be really helpful if you could change download info in your readme from 'com.akexorcist:snaptimepicker:1.0.0' to 'com.akexorcist:snap-time-picker:1.0.0'. Thank you. 

![image](https://user-images.githubusercontent.com/48484782/66714286-3f65a400-edb5-11e9-8520-8ab7e143fa2f.png)

**Comment by akexorcist** [comment]
Fixed! Thank you for your feedback.
