### ISSUE TITLE
How can use this library by java

### ISSUE THREAD

**Issue by enggazzar** [akexorcist/SnapTimePicker#7]
Iam working in project by java i can't use this library

**Comment by giampa-cz** [comment]
You can use it by Java. In Android Studio just include the library in your gradle and use it like this:

```
SnapTimePickerDialog picker = new SnapTimePickerDialog.Builder()
            .setPreselectedTime(new TimeValue(3, 40))
            .build();

picker.setListener((hourOfDay, minute) -> {
         [...]
    }
picker.show(getFragmentManager(), TAG);
```

You project must use androidX.

**Comment by enggazzar** [comment]
Thanks for replay but i have this issues
picker.setListener(new SnapTimePickerDialog.Listener() {
                    ^
  class file for kotlin.jvm.functions.Function2 not found

**Comment by giampa-cz** [comment]
You need to enable Kotlin in your project, even if is Java based.

**Comment by enggazzar** [comment]
Thnks
